### ISSUE TITLE
Consider switching to from letsencrypt crontab to lua-resty-open-ssl

### ISSUE THREAD

**Issue by Valian** [reef-technologies/cookiecutter-rt-django#33]
There's a very neat alternative to letsencrypt CLI - https://github.com/auto-ssl/lua-resty-auto-ssl#lua-resty-auto-ssl. It's OpenResty (nginx with lua support) module generating and renewing certificates on-the-fly, as they're requested. I've created a pretty popular docker image making it very easy to use https://github.com/Valian/docker-nginx-auto-ssl

```yaml
# docker-compose.yml
version: '3'
services:
  # your application, listening on port specified in `SITES` env variable
  myapp:
    image: nginx

  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: 'yourdomain.com'
      SITES: 'yourdomain.com=myapp:80'
  

volumes:
  ssl_data:
```

No crontab, no hassle, it just works. Can be integrated directly into nginx serving media / static files.
