### ISSUE TITLE
Add automatic code checks / formatting

### ISSUE THREAD

**Issue by Valian** [reef-technologies/cookiecutter-rt-django#36]
I'm usually using tool called `pre-commit` https://pre-commit.com/

It's something that works great as an addition to CI / CD. Just before making a commit, pre-commit automatically runs all changed files through a series of fast checks, such as flake8, black, isort etc. It usually takes less than a second, and makes it possible to eliminate style-related discussion during Code Review.  

My usual configuration file:

```yaml
repos:
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.8
        args: ['--line-length=120']
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.6.0
    hooks:
      - id: seed-isort-config
        language_version: python3.8
        args: ['--application-directories=src/backend']
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: flake8
        language_version: python3
```
